name: Alerta Discord

on:
  push:
    branches:
      - '**'         
  pull_request:
    types: [closed]
    branches:
      - main        

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Informar alerta no Discord
        uses: Ilshidur/action-discord@v0.4.0      
        with:
          args: |
            🚀 Repositório **${{ github.repository }}** recebeu um evento `${{ github.event_name }}`  
            Branch: `${{ github.ref }}`  
            Autor: `${{ github.actor }}`  
            Commit: `${{ github.sha }}`  
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
